"""How many signs would our own dataset need?

Uses the same frequency proxy and matching as analysis/coverage/coverage.py
(wordfreq English, lemmatised; articles, copulas and auxiliaries excluded as
text-to-gloss drops them) and asks three questions:

  1. What share of everyday words does each dataset we know of sign?
  2. If we recorded our own dataset, choosing the most frequent words first,
     what share would N signs cover?
  3. Starting from PopSign (which we can ship), how many *new* signs would
     reach 80%, 90%, 95%?

Writes showcase/COVERAGE.md (a metric output: numbers only, no sign data)
and showcase/target_words.txt, the words a dictionary fetcher such as the
Signing Savvy one should look up first.

    python showcase/coverage_curve.py

Caveat: one English lemma is treated as one sign. Real ASL does not map word
to word (one sign can cover several English words, and one English word can
need different signs by meaning), so read these as the order of magnitude,
not exact counts.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "analysis" / "coverage"))

import coverage as cov  # noqa: E402

SIZES = [250, 500, 1000, 2000, 3000, 5000, 10000]
TARGETS = [0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
TARGET_WORDS = 5000


def ranked_signable(freq):
    kept = {w: f for w, f in freq.items() if w not in cov.NOT_SIGNED}
    total = sum(kept.values())
    ranked = sorted(kept, key=kept.get, reverse=True)
    return ranked, kept, total


def share(lexicon, kept, total) -> float:
    return sum(f for w, f in kept.items() if w in lexicon) / total


def needed(start, ranked, kept, total, target):
    """New signs to add to `start`, most frequent first, to reach target; None if never."""
    covered = sum(f for w, f in kept.items() if w in start)
    added = 0
    for word in ranked:
        if covered / total >= target:
            return added
        if word not in start:
            covered += kept[word]
            added += 1
    return added if covered / total >= target else None


def main() -> int:
    freq = cov.frequency_by_lemma()
    ranked, kept, total = ranked_signable(freq)
    pop, citizen = cov.load_popsign(), cov.load_asl_citizen()

    lines = [
        "# How many signs would our own dataset need?",
        "",
        "Generated by `python showcase/coverage_curve.py`. Do not edit by hand.",
        "",
        "Share of everyday signable words (by how often they are used, from `wordfreq`'s "
        "English list, which includes film and TV subtitles) that a lexicon has a sign for. "
        "Articles, *be*, *do* and *have* are left out because ASL does not sign them as words. "
        "One English lemma is counted as one sign, which real ASL does not do exactly, so treat "
        "these numbers as estimates.",
        "",
        "## 1. Datasets we know of",
        "",
        "| Lexicon | Words | Everyday words signed | Commercial use |",
        "|---|---|---|---|",
        f"| PopSign ASL v1.0 (prototype today) | {len(pop):,} | **{share(pop, kept, total):.0%}** | yes (CC BY 4.0) |",
        f"| ASL Citizen | {len(citizen):,} | **{share(citizen, kept, total):.0%}** | no (non-commercial, by permission) |",
        f"| PopSign + ASL Citizen | {len(pop | citizen):,} | "
        f"**{share(pop | citizen, kept, total):.0%}** | no |",
        "",
        "## 2. Our own dataset, recording the most-used words first",
        "",
        "| Signs recorded | Everyday words signed |",
        "|---|---|",
    ]
    for n in SIZES:
        lines.append(f"| {n:,} | **{share(set(ranked[:n]), kept, total):.0%}** |")

    lines += [
        "",
        "## 3. New signs to record on top of what we have",
        "",
        "| Target | Starting from nothing | Starting from PopSign (shippable) | "
        "Starting from PopSign + ASL Citizen (if Microsoft agrees) |",
        "|---|---|---|---|",
    ]

    def fmt(value):
        return "not reached" if value is None else f"{value:,}"

    for target in TARGETS:
        lines.append(f"| {target:.0%} | {fmt(needed(set(), ranked, kept, total, target))} | "
                     f"{fmt(needed(pop, ranked, kept, total, target))} | "
                     f"{fmt(needed(pop | citizen, ranked, kept, total, target))} |")

    gaps = [w for w in ranked if w not in (pop | citizen)][:60]
    lines += [
        "",
        "## The most-used words no dataset we hold can sign",
        "",
        "These would be first on our own recording list. Some (*as, by, would*) are "
        "usually not signed as separate words in ASL; a Deaf reviewer should cut this list.",
        "",
        ", ".join(gaps),
        "",
        "Names, places and anything else without a sign are fingerspelled once the letters "
        "are in (prototype/README.md, Fingerspelling).",
        "",
    ]
    out = HERE / "COVERAGE.md"
    out.write_text("\n".join(lines), encoding="utf-8")

    # The words a dictionary fetcher should look up, most-used first.
    targets = [w for w in ranked if w.isalpha()][:TARGET_WORDS]
    (HERE / "target_words.txt").write_text(
        f"# The {len(targets):,} most-used signable English lemmas, most-used first.\n"
        "# Generated by showcase/coverage_curve.py; used by dictionary fetchers.\n"
        + "\n".join(targets) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
