"""
Run the corpus pipeline end to end on synthetic data.

Proves the plumbing works before it is pointed at a real corpus, so time on the
training machine goes into training rather than into debugging an argument
name. Stages whose dependencies are not installed are skipped and reported as
skipped, never as passed.

    python tools/smoke_test.py            # temp dir, cleaned up
    python tools/smoke_test.py --keep     # leave the artefacts for inspection
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from typing import List, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "corpus"))

SKIP, PASS, FAIL = "skip", "pass", "FAIL"


def have(module: str) -> bool:
    return importlib.util.find_spec(module) is not None


def synth_person(width: int = 400, height: int = 800):
    """A crude standing figure: enough for the pipeline, not for a model."""
    import cv2
    import numpy as np

    image = np.full((height, width, 3), 190, dtype=np.uint8)
    mask = np.zeros((height, width, 3), dtype=np.uint8)

    cx = width // 2
    parts = [
        ((cx - 45, int(height * 0.06)), (cx + 45, int(height * 0.20))),   # head
        ((cx - 80, int(height * 0.20)), (cx + 80, int(height * 0.55))),   # torso
        ((cx - 115, int(height * 0.22)), (cx - 80, int(height * 0.50))),  # arms
        ((cx + 80, int(height * 0.22)), (cx + 115, int(height * 0.50))),
        ((cx - 70, int(height * 0.55)), (cx - 10, int(height * 0.96))),   # legs
        ((cx + 10, int(height * 0.55)), (cx + 70, int(height * 0.96))),
    ]
    for top_left, bottom_right in parts:
        cv2.rectangle(image, top_left, bottom_right, (120, 110, 100), -1)
        cv2.rectangle(mask, top_left, bottom_right, (255, 255, 255), -1)
    return image, mask


def build_corpus(root: str, count: int = 4) -> Tuple[str, str, str]:
    import cv2

    from provenance import Manifest, Record, now_iso

    raw_dir, mask_dir = os.path.join(root, "raw"), os.path.join(root, "masks")
    os.makedirs(raw_dir, exist_ok=True)
    os.makedirs(mask_dir, exist_ok=True)
    manifest = Manifest(os.path.join(root, "provenance.jsonl"))

    for index in range(count):
        name = f"synthetic-{index:03d}.png"
        image, mask = synth_person()
        cv2.imwrite(os.path.join(raw_dir, name), image)
        cv2.imwrite(os.path.join(mask_dir, name), mask)
        manifest.add(Record(
            image_id=os.path.splitext(name)[0],
            source="own-recording",
            source_url="synthetic://smoke-test",
            licence="commercial-release",
            retrieved_at=now_iso(),
            notes="Generated by smoke_test.py. Not real data.",
        ))
    return raw_dir, mask_dir, manifest.path


def stage_unit_tests() -> Tuple[str, str]:
    result = subprocess.run([sys.executable, os.path.join(HERE, "tests", "test_toolkit.py")],
                            capture_output=True, text=True)
    tail = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else "no output"
    return (PASS if result.returncode == 0 else FAIL), tail


def stage_licence_gate(root: str) -> Tuple[str, str]:
    """The gate must refuse a disallowed source. If it does not, nothing else matters."""
    from provenance import LicenceError, Manifest, Record, now_iso

    manifest = Manifest(os.path.join(root, "gate-probe.jsonl"))
    for source in ("shhq", "pexels", "some-random-scraper"):
        try:
            manifest.add(Record(image_id=f"probe-{source}", source=source, source_url="u",
                                licence="whatever", retrieved_at=now_iso()))
        except LicenceError:
            continue
        return FAIL, f"the gate accepted {source!r}"
    return PASS, "shhq, pexels and unknown sources all refused"


def stage_build_archive(root: str, raw_dir: str, mask_dir: str, manifest_path: str) -> Tuple[str, str]:
    import clean_to_images

    out = os.path.join(root, "frames.zip")
    report = clean_to_images.build(raw_dir, mask_dir, manifest_path, out,
                                   resolution=256, prefix="sshq")
    with zipfile.ZipFile(out) as archive:
        names = archive.namelist()
    expected = len(os.listdir(raw_dir))
    if report["images_written"] != expected or len(names) != expected:
        return FAIL, f"expected {expected} images, archive holds {len(names)}"
    if names[0] != "sshq00000/img00000000.png":
        return FAIL, f"unexpected archive layout: {names[0]}"
    if not os.path.exists(os.path.join(root, "frames.provenance.json")):
        return FAIL, "provenance sidecar not written"
    return PASS, f"{len(names)} images, layout matches upstream, sidecar written"


def stage_filter(raw_dir: str, root: str) -> Tuple[str, str]:
    if not have("mediapipe"):
        return SKIP, "mediapipe not installed (CPU package, safe to install anywhere)"
    sys.path.insert(0, HERE)
    import mp_compat  # noqa: PLC0415

    if not mp_compat.available():
        return SKIP, f"installed mediapipe has no Solutions API — need {mp_compat.REQUIRED_PIN}"
    result = subprocess.run(
        [sys.executable, os.path.join(HERE, "corpus", "filter_candidates.py"),
         "--input_dir", raw_dir, "--output_dir", os.path.join(root, "filtered"),
         "--rejects_log", os.path.join(root, "rejected.json")],
        capture_output=True, text=True)
    if result.returncode != 0:
        return FAIL, result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "non-zero exit"
    # Synthetic rectangles are not expected to pass a real pose detector; the
    # point is that the script runs and reports rather than crashing.
    return PASS, result.stdout.strip().splitlines()[0] if result.stdout.strip() else "ran"


def stage_masks(raw_dir: str, root: str) -> Tuple[str, str]:
    if not have("rembg"):
        return SKIP, "rembg not installed (CPU inference, no GPU needed)"
    result = subprocess.run(
        [sys.executable, os.path.join(HERE, "corpus", "make_masks.py"),
         "--input_dir", raw_dir, "--output_dir", os.path.join(root, "masks-generated")],
        capture_output=True, text=True)
    if result.returncode != 0:
        return FAIL, result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "non-zero exit"
    return PASS, result.stdout.strip().splitlines()[0] if result.stdout.strip() else "ran"


def stage_eval_imports() -> Tuple[str, str]:
    sys.path.insert(0, os.path.join(HERE, "eval"))
    import metrics  # noqa: PLC0415

    if not have("mediapipe") or not have("pose_format"):
        missing = [name for name in ("mediapipe", "pose_format") if not have(name)]
        return SKIP, f"metrics import fine; scoring needs {', '.join(missing)} (both CPU-only)"

    sys.path.insert(0, HERE)
    import mp_compat  # noqa: PLC0415

    if not mp_compat.available():
        return SKIP, f"imports fine; scoring needs {mp_compat.REQUIRED_PIN}"
    import pose_fidelity  # noqa: F401, PLC0415
    import run_eval  # noqa: F401, PLC0415
    return PASS, "eval harness imports cleanly"


def stage_cli_help() -> Tuple[str, str]:
    """Every script should at least parse its own arguments."""
    scripts = [
        os.path.join(HERE, "corpus", "clean_to_images.py"),
        os.path.join(HERE, "corpus", "fetch_pixabay.py"),
        os.path.join(HERE, "pin_baseline.py"),
        os.path.join(HERE, "preflight.py"),
        os.path.join(HERE, "inspect_lexicon.py"),
    ]
    broken = []
    for script in scripts:
        result = subprocess.run([sys.executable, script, "--help"], capture_output=True, text=True)
        if result.returncode != 0:
            broken.append(f"{os.path.basename(script)}: {result.stderr.strip().splitlines()[-1:]}")
    if broken:
        return FAIL, "; ".join(broken)
    return PASS, f"{len(scripts)} CLIs parse"


def main() -> None:
    parser = argparse.ArgumentParser(description="End-to-end smoke test on synthetic data.")
    parser.add_argument("--keep", action="store_true", help="Do not delete the working directory")
    args = parser.parse_args()

    if not have("cv2") or not have("numpy") or not have("PIL"):
        sys.exit("needs numpy, opencv-python-headless and Pillow: pip install -r tools/requirements.txt")

    root = tempfile.mkdtemp(prefix="aslytics-smoke-")
    results: List[Tuple[str, str, str]] = []

    def record(name: str, outcome: Tuple[str, str]) -> None:
        results.append((outcome[0], name, outcome[1]))

    try:
        record("unit tests", stage_unit_tests())
        record("licence gate", stage_licence_gate(root))
        raw_dir, mask_dir, manifest_path = build_corpus(root)
        record("synthetic corpus", (PASS, f"{len(os.listdir(raw_dir))} images + masks + provenance"))
        record("build archive", stage_build_archive(root, raw_dir, mask_dir, manifest_path))
        record("filter_candidates", stage_filter(raw_dir, root))
        record("make_masks", stage_masks(raw_dir, root))
        record("eval harness", stage_eval_imports())
        record("CLI arguments", stage_cli_help())
    finally:
        if args.keep:
            print(f"\nworking directory kept at {root}\n")
        else:
            shutil.rmtree(root, ignore_errors=True)

    width = max(len(name) for _, name, _ in results)
    print("\nsmoke test\n")
    for status, name, detail in results:
        print(f"  {status:>4}  {name.ljust(width)}  {detail}")

    failures = [name for status, name, _ in results if status == FAIL]
    skipped = [name for status, name, _ in results if status == SKIP]
    print(f"\n{len(results) - len(failures) - len(skipped)} passed, "
          f"{len(skipped)} skipped, {len(failures)} failed")
    if skipped:
        print("Skipped stages need CPU-only packages — install them before the real run, "
              "not on the training machine's clock.")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
